#include "../lfgui/image.cpp"
#include "../lfgui/font.cpp"
#include "../lfgui/lfgui.cpp"
#include "../lfgui/lineedit.cpp"
#include "../lfgui/slider.cpp"
#include "../lfgui/window.cpp"
#include "../common_sample_code.cpp"
